### ISSUE TITLE
Describe how to run Ubuntu on Windows 10

### ISSUE THREAD

**Issue by prolike** [prolike/prolike-stack#1]
@LouBNielsen found an offical way to run an ubuntu terminal on Win10, that seems to run on a virtual  machine or container, that allows us to install using apt-get etc.

Louise will write a small instruction here for other Win10 users to follow

**Comment by LouBNielsen** [comment]
https://itsfoss.com/install-bash-on-windows/

**Comment by LouBNielsen** [comment]
https://www.maketecheasier.com/install-zsh-and-oh-my-zsh-windows10/
- This i the one i followed.. :-)
